import "./globals.css";

export const metadata = {
  // title: "Ideal Gym",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
            <main className="">
              {children}
            </main>
      </body>
    </html>
  );
}
