import "../globals.css";
import Footer from "@/components/Footer";
import { Appbar } from "@/components/Header";
import { Providers } from "@/app/Redux/Provider";



export const metadata = {
  title: "Ideal Gym",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <section className="myfont flex flex-col min-h-screen max-h-full bg-black" >
        <Providers>
            < Appbar />
            <main className="flex-grow max-w-screen-xl w-full flex flex-col mx-auto">
              {children}
            </main>
            <Footer />
          </Providers>
        </section>

      </body>
    </html>
  );
}
